#!/bin/bash

FC=gfortran

$FC -c kind.f90
$FC -c freemod.f90
$FC -c input_free.f90
$FC -c recips.f90
$FC -c set_lattice.f90
$FC -c calculate_radius.f90
$FC -c ggen.f90
$FC -c hpsort.f90
$FC -c gaussian.f90
$FC -c kgen.f90
$FC -c set_hamiltonian.f90
$FC -c deallocate_all.f90
$FC -c free_dos.f90
$FC -o free_dos.x *.o 
